name: Python Tests

on:
  push:
    branches:
      - main
      - feature/AI-Quest
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - run: pytest
